language: go

go:
  - 1.6
  - tip

go_import_path: golang.org/x/crypto/sha3

install:
  - go get github.com/jinzhu/gorm
  - go get github.com/dgrijalva/jwt-go
  - go get github.com/go-martini/martini

script: go test -v ./...
