language: go

go:
  - 1.6

services:
  - postgresql

install:
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
  - go get github.com/tools/godep
  - godep restore

before_script:
  - psql -c 'create database postgresdb;' -U postgres

script: go test -v ./...

