language: go

go:
  - 1.6
  - tip

services:
  - postgresql

before_script:
  - psql -c 'create database postgresdb;' -U postgres

before_install:
  - export GOPATH=${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH
  - export PATH=${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH

script: go test -v ./...
