language: go

go:
  - 1.6

install:
  - go get github.com/jinzhu/gorm
  - go get github.com/dgrijalva/jwt-go
  - go get github.com/go-martini/martini
  - go get github.com/jinzhu/gorm/dialects/postgres
  - go get github.com/lib/pq
  - go get golang.org/x/crypto/sha3

script: go test -v ./...

